# Generated by Django 3.1.2 on 2020-10-12 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca', '0002_auto_20201012_1057'),
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=20, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('descripcioncorta', models.CharField(max_length=250, null=True)),
                ('detalle', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('palabrasclave', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(max_length=1, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='FK_productoCategoria', to='categoria.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='FK_productoCategoria', to='marca.marca')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
    ]
