# Generated by Django 3.1.2 on 2020-10-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcioncorta',
            new_name='descripcion_corta',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='palabrasclave',
            new_name='palabras_clave',
        ),
    ]
