# Generated by Django 3.1.2 on 2020-10-20 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=20, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('descripcion_corta', models.CharField(max_length=250, null=True)),
                ('detalle', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('palabras_clave', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(max_length=1, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='FK_productoCategoria', to='producto.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='FK_productoCategoria', to='producto.marca')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
    ]
