# Generated by Django 3.1.2 on 2020-10-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20201025_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='twitter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
