# Generated by Django 3.1.2 on 2020-10-26 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_empresa_twitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='id',
            new_name='idCurso',
        ),
    ]
