# Generated by Django 3.1.2 on 2020-10-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20201026_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
