# Generated by Django 3.1.2 on 2020-10-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marca',
            table='marca',
        ),
    ]
