# Generated by Django 3.1.2 on 2020-10-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
    ]
