# Generated by Django 3.1.2 on 2020-10-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='emailcontacto',
            new_name='email_contacto',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='quienessomos',
            new_name='quienes_somos',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='telefonocontacto',
            new_name='telefono_contacto',
        ),
    ]
